---
engines:
  # PHP analysis
  phpstan:
    enabled: true
  pmd:
    enabled: true
  eslint:
    enabled: true
  trivy:
    enabled: true

exclude_paths:
  - "vendor/**"
  - "node_modules/**"
  - "storage/**"
  - "bootstrap/cache/**"
  - "public/storage/**"
  - "tests/**"
  - ".git/**"
  - "*.log"
  - "*.tmp"
  - "coverage/**"
  - "build/**"
  - "dist/**"
  - ".env*"
  - "composer.lock"
  - "package-lock.json"
  - "yarn.lock"
  - "phpunit.xml"
  - "phpcs.xml*"
  - "rules.json"
  - "postcss.config.js"
  - "tailwind.config.js"
  - "vite.config.js"
  - "eslint.config.js"
  # Additional exclusions for PHPMD
  - ".codacy.yml"
  - ".editorconfig"
  - ".eslintignore"
  - ".eslintrc.json"
  - ".gitattributes"
  - ".gitignore"
  - ".htaccess"
  - ".phpunit.result.cache"
  - ".stylelintrc.json"
  - "artisan"
  - "composer.json"
  - "favicon.ico"
  - "package.json"
  - "index.php"
  - "phpcs-strict-lines.xml"
  - "phpinsights.php"
  - "README.md"
  - ".codacy/**"
  - ".cursor/**"
  - ".github/**"
  - ".idea/**"