import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: 'module',
            globals: {
                jQuery: 'readonly',
                $: 'readonly',
                console: 'readonly',
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                FormData: 'readonly',
                URLSearchParams: 'readonly',
                FileReader: 'readonly',
                CustomEvent: 'readonly',
                IntersectionObserver: 'readonly',
                performance: 'readonly',
                requestAnimationFrame: 'readonly',
                getComputedStyle: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                module: 'readonly',
                define: 'readonly',
                self: 'readonly',
                bootstrap: 'readonly'
            }
        },
        rules: {
            'indent': 'off',
            'quotes': 'off',
            'semi': 'off',
            'no-unused-vars': 'warn',
            'no-console': 'warn',
            'no-undef': 'off',
            'no-sparse-arrays': 'off',
            'no-func-assign': 'off',
            'no-redeclare': 'off',
            'no-cond-assign': 'off',
            'no-prototype-builtins': 'off',
            'no-empty': 'off',
            'no-useless-escape': 'off',
            'no-unused-expressions': 'off',
            'no-var': 'off',
            'prefer-const': 'off',
            'prefer-arrow-callback': 'off',
            'arrow-spacing': 'off',
            'object-curly-spacing': 'off',
            'array-bracket-spacing': 'off',
            'comma-dangle': 'off',
            'comma-spacing': 'off',
            'comma-style': 'off',
            'computed-property-spacing': 'off',
            'func-call-spacing': 'off',
            'key-spacing': 'off',
            'keyword-spacing': 'off',
            'no-multi-spaces': 'off',
            'no-trailing-spaces': 'off',
            'object-property-newline': 'off',
            'padded-blocks': 'off',
            'space-before-blocks': 'off',
            'space-before-function-paren': 'off',
            'space-in-parens': 'off',
            'space-infix-ops': 'off',
            'space-unary-ops': 'off',
            'spaced-comment': 'off',
            'template-curly-spacing': 'off',
            'yield-star-spacing': 'off'
        },
        ignores: []
    }
];
