import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: 'module',
            globals: {
                jQuery: 'readonly',
                $: 'readonly',
                console: 'readonly',
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                FormData: 'readonly',
                URLSearchParams: 'readonly',
                FileReader: 'readonly',
                CustomEvent: 'readonly',
                IntersectionObserver: 'readonly',
                performance: 'readonly',
                requestAnimationFrame: 'readonly',
                getComputedStyle: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                module: 'readonly',
                define: 'readonly',
                self: 'readonly',
                bootstrap: 'readonly'
            }
        },
        rules: {
            // Envato Standards - Code Quality
            'indent': ['error', 4],
            'quotes': ['error', 'single'],
            'semi': ['error', 'always'],
            'no-unused-vars': 'error',
            'no-console': 'warn',
            'no-undef': 'error',
            'no-sparse-arrays': 'error',
            'no-func-assign': 'error',
            'no-redeclare': 'error',
            'no-cond-assign': 'error',
            'no-prototype-builtins': 'error',
            'no-empty': 'error',
            'no-useless-escape': 'error',
            'no-unused-expressions': 'error',
            'no-var': 'error',
            'prefer-const': 'error',
            'prefer-arrow-callback': 'error',
            'arrow-spacing': 'error',
            'object-curly-spacing': ['error', 'always'],
            'array-bracket-spacing': ['error', 'never'],
            'comma-dangle': ['error', 'never'],
            'comma-spacing': ['error', { 'before': false, 'after': true }],
            'comma-style': ['error', 'last'],
            'computed-property-spacing': ['error', 'never'],
            'func-call-spacing': ['error', 'never'],
            'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
            'keyword-spacing': ['error', { 'before': true, 'after': true }],
            'no-multi-spaces': 'error',
            'no-trailing-spaces': 'error',
            'object-property-newline': ['error', { 'allowMultiplePropertiesPerLine': false }],
            'padded-blocks': ['error', 'never'],
            'space-before-blocks': 'error',
            'space-before-function-paren': ['error', 'never'],
            'space-in-parens': ['error', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': 'error',
            'spaced-comment': ['error', 'always'],
            'template-curly-spacing': 'error',
            'yield-star-spacing': 'error',

            // Envato Standards - Security
            'no-eval': 'error',
            'no-implied-eval': 'error',
            'no-new-func': 'error',
            'no-script-url': 'error',
            'no-alert': 'warn',
            'no-debugger': 'error',
            'no-duplicate-case': 'error',
            'no-duplicate-imports': 'error',
            'no-empty-character-class': 'error',
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-extra-semi': 'error',
            'no-fallthrough': 'error',
            'no-global-assign': 'error',
            'no-import-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-obj-calls': 'error',
            'no-regex-spaces': 'error',
            'no-self-assign': 'error',
            'no-sparse-arrays': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',

            // Envato Standards - Performance
            'no-loop-func': 'error',
            'no-new-object': 'error',
            'no-new-wrappers': 'error',
            'no-array-constructor': 'error',
            'no-new-require': 'error',
            'no-path-concat': 'error',
            'no-process-env': 'warn',
            'no-process-exit': 'warn',
            'no-sync': 'warn',

            // Envato Standards - Best Practices
            'accessor-pairs': 'error',
            'array-callback-return': 'error',
            'block-scoped-var': 'error',
            'class-methods-use-this': 'warn',
            'complexity': ['warn', 10],
            'consistent-return': 'error',
            'curly': 'error',
            'default-case': 'error',
            'dot-location': ['error', 'property'],
            'dot-notation': 'error',
            'eqeqeq': 'error',
            'guard-for-in': 'error',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-div-regex': 'error',
            'no-else-return': 'error',
            'no-empty-function': 'error',
            'no-empty-pattern': 'error',
            'no-eq-null': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-label': 'error',
            'no-floating-decimal': 'error',
            'no-implicit-coercion': 'error',
            'no-implicit-globals': 'error',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-magic-numbers': ['warn', { 'ignore': [0, 1, -1] }],
            'no-multi-assign': 'error',
            'no-multi-str': 'error',
            'no-nested-ternary': 'error',
            'no-new': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'error',
            'no-proto': 'error',
            'no-return-assign': 'error',
            'no-return-await': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-throw-literal': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unused-labels': 'error',
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-useless-return': 'error',
            'no-void': 'error',
            'no-warning-comments': 'warn',
            'no-with': 'error',
            'prefer-promise-reject-errors': 'error',
            'radix': 'error',
            'require-await': 'error',
            'vars-on-top': 'error',
            'wrap-iife': 'error',
            'yoda': 'error'
        },
        ignores: []
    }
];
